# Generated by Django 4.2 on 2023-05-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_employee_eid_alter_employee_esalary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ecostcenter',
            new_name='costcenter',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='edept',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='edesignation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='elocation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ereportingto',
            new_name='reportingto',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esalary',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=1),
        ),
    ]
